version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "5038:5038"
    volumes:
      - ./api:/app
      - /app/node_modules
  todoapp:
    build: ./todoapp
    container_name: todoapp_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
